name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: swift test
    runs-on: [self-hosted, ARM64]
    steps:
      - uses: actions/checkout@v4
      - run: swift test
